### ISSUE TITLE
can you give a thought to my suggestion?

### ISSUE THREAD

**Issue by fuyunwang** [FutureTwT/Image-Hashing-Baselines#1]
It is extremely infusive if you can provide a repository for sequential recommendation baselines with graph neural networks and transformer!

What's more, sequential recommendation is only a special case, which corresponds to the process of processing discrete or continuous sequence data with different levels of graph neural networks!!!

**Comment by FutureTwT** [comment]
If there are plans for related research in the future, there will be corresponding open-source work.
